// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApyQR3Pv7i4n0eQcno4841rH4MOnmG5LA',
    appId: '1:774089458894:web:87d4036de46901abe37c9f',
    messagingSenderId: '774089458894',
    projectId: 'nid-portal',
    authDomain: 'nid-portal.firebaseapp.com',
    storageBucket: 'nid-portal.appspot.com',
    measurementId: 'G-ER8YHRBJND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMx45NHS21PEYrJac-ykXrqpIZ_uHZXRM',
    appId: '1:774089458894:android:c8f642bcbbeed4aee37c9f',
    messagingSenderId: '774089458894',
    projectId: 'nid-portal',
    storageBucket: 'nid-portal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqpwB4bWlDk17j6vg7W3ENAnw_PoyqMz4',
    appId: '1:774089458894:ios:2957e865ae356ceae37c9f',
    messagingSenderId: '774089458894',
    projectId: 'nid-portal',
    storageBucket: 'nid-portal.appspot.com',
    iosClientId: '774089458894-35cr6ibbf4hp4cnk1gckfd2nv9dd9mf1.apps.googleusercontent.com',
    iosBundleId: 'bornomala.nid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqpwB4bWlDk17j6vg7W3ENAnw_PoyqMz4',
    appId: '1:774089458894:ios:0488067819da5f9be37c9f',
    messagingSenderId: '774089458894',
    projectId: 'nid-portal',
    storageBucket: 'nid-portal.appspot.com',
    iosClientId: '774089458894-k5fvbmfcd3kg4tcg8clf91hlp5q2fouu.apps.googleusercontent.com',
    iosBundleId: 'bornomala.nid.RunnerTests',
  );
}
